### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by queenofdexterity** [queenofdexterity/BingeFlix#6]
- [ ] Users can search for movies by title
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by s-pangburn** [comment]
- [ ] When I refresh the page on the search to nothing shows up. It should either redirect me to the index or show the same search/results.
- [ ] I can't play any movies from the splash image that pops up, instead this error shows up:
![screen shot 2018-02-09 at 1 21 09 pm](https://user-images.githubusercontent.com/8031316/36050783-afa9c61a-0d9c-11e8-8ae1-53c1db551c10.png)

**Comment by queenofdexterity** [comment]
Oh, wow. I think I just fixed both issues. Let me know! Thanks.

**Comment by s-pangburn** [comment]
All good now! Great work Areej! 👏
